//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.21 at 10:54:40 오전 KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.openflamingo.org/schema/collector", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openflamingo.model.collector;
