CREATE DATABASE IF NOT EXISTS FLAMINGO DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

DROP TABLE IF EXISTS ACTION_HISTORY;
DROP TABLE IF EXISTS WORKFLOW_HISTORY;
DROP TABLE IF EXISTS HIVE_HISTORY;
DROP TABLE IF EXISTS AUDIT_LOG;

CREATE TABLE WORKFLOW_HISTORY (
  ID              INT(11)      NOT NULL AUTO_INCREMENT COMMENT 'Sequence',
  WORKFLOW_ID     VARCHAR(60)  NOT NULL COMMENT 'Workflow String ID',
  JOB_ID          INT(11)      NOT NULL COMMENT 'Job ID',
  JOB_ID_STRING   VARCHAR(60)  NOT NULL COMMENT 'Job String ID',
  WORKFLOW_NAME   VARCHAR(250) NOT NULL COMMENT 'Workflow Name',
  CURRENT_ACTION  VARCHAR(250) DEFAULT '' COMMENT 'Current Action',
  JOB_NAME        VARCHAR(250) NOT NULL COMMENT 'Workflow Name',
  WORKFLOW_XML    BLOB         NOT NULL COMMENT 'Workflow XML',
  VARIABLE        BLOB         DEFAULT NULL COMMENT 'Workflow Varialbe',
  START_DATE      DATETIME     COMMENT 'Start Date',
  END_DATE        DATETIME     COMMENT 'End Date',
  CAUSE           VARCHAR(250) DEFAULT '' COMMENT 'cause',
  CURRENT_STEP    INTEGER      DEFAULT NULL COMMENT 'Current Step',
  TOTAL_STEP      INTEGER      DEFAULT NULL COMMENT 'Total Step',
  ELAPSED         INTEGER      DEFAULT NULL COMMENT 'Elapsed Time',
  EXCEPTION       BLOB         DEFAULT NULL COMMENT 'Description',
  STATUS          VARCHAR(10)  NOT NULL COMMENT 'Workflow Status',
  USERNAME        VARCHAR(50)  NOT NULL COMMENT 'Writer',
  JOB_TYPE        VARCHAR(20)  NOT NULL COMMENT 'Job Type',
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE ACTION_HISTORY (
  ID              INT(11)      NOT NULL AUTO_INCREMENT COMMENT 'Sequence',
  WORKFLOW_ID     VARCHAR(60)  NOT NULL COMMENT 'Workflow String ID',
  JOB_ID          INT(11)      NOT NULL COMMENT 'Job ID',
  JOB_ID_STRING   VARCHAR(60)  NOT NULL COMMENT 'Job String ID',
  ACTION_NAME     VARCHAR(250) NOT NULL COMMENT 'Action Name',
  WORKFLOW_NAME   VARCHAR(250) NOT NULL COMMENT 'Workflow Name',
  JOB_NAME        VARCHAR(250) NOT NULL COMMENT 'Workflow Name',
  START_DATE      DATETIME     COMMENT 'Start Date',
  END_DATE        DATETIME     COMMENT 'End Date',
  CAUSE           VARCHAR(250) DEFAULT '' COMMENT 'cause',
  CURRENT_STEP    INTEGER      DEFAULT NULL COMMENT 'Current Step',
  TOTAL_STEP      INTEGER      DEFAULT NULL COMMENT 'Total Step',
  ELAPSED         INTEGER      DEFAULT NULL COMMENT 'Elapsed Time',
  LOG_PATH        VARCHAR(255) DEFAULT NULL COMMENT 'Log Path',
  SCRIPT          BLOB         DEFAULT '' COMMENT 'Script',
  COMMAND         BLOB         DEFAULT '' COMMENT 'Command Line',
  EXCEPTION       BLOB         DEFAULT '' COMMENT 'Exception',
  STATUS          VARCHAR(10)  NOT NULL COMMENT 'Workflow Status',
  USERNAME        VARCHAR(50)  NOT NULL COMMENT 'Writer',
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE HIVE_HISTORY (
  ID              INT(11)      NOT NULL AUTO_INCREMENT COMMENT 'Sequence',
  EXECUTION_ID    VARCHAR(60)  NOT NULL COMMENT 'Hive Query Execution ID',
  DB_NAME         VARCHAR(250) NOT NULL COMMENT 'Hive Query Database Name',
  QUERY_NAME      VARCHAR(250) NOT NULL COMMENT 'Hive Query Name',
  LOG_PATH        VARCHAR(255) DEFAULT NULL COMMENT 'Log Path',
  HIVE_JSON       BLOB         DEFAULT '' COMMENT 'Hive JSON',
  QUERY           BLOB         DEFAULT '' COMMENT 'Hive Query',
  START_DATE      DATETIME     COMMENT 'Start Date',
  END_DATE        DATETIME     COMMENT 'End Date',
  ELAPSED         INTEGER      DEFAULT NULL COMMENT 'Elapsed Time',
  CAUSE           BLOB         DEFAULT '' COMMENT 'cause',
  STATUS          VARCHAR(10)  NOT NULL COMMENT 'Hive Query Execution Status',
  USERNAME        VARCHAR(50)  NOT NULL COMMENT 'Writer',
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;

CREATE TABLE AUDIT_LOG (
  ID              INT(11)      NOT NULL AUTO_INCREMENT COMMENT 'Sequence',
  CLUSTER_ID      INT(11)      DEFAULT NULL COMMENT 'Hadoop Cluster Identifier',
  CLUSTER_NAME    VARCHAR(250) DEFAULT NULL COMMENT 'Hadoop Cluster Name',
  FROM_PATH       TEXT         DEFAULT NULL COMMENT 'From Path',
  TO_PATH         TEXT         DEFAULT NULL COMMENT 'To Path',
  LENGTH          LONG         DEFAULT NULL COMMENT 'Total File Size',
  FS_TYPE         VARCHAR(50)  NOT NULL COMMENT 'File System Type',
  AUDIT_TYPE      VARCHAR(50)  NOT NULL COMMENT 'Audit Type',
  FILE_TYPE       VARCHAR(50)  NOT NULL COMMENT 'File Type',
  WORK_DATE       DATETIME     COMMENT 'Work Date',
  USERNAME        VARCHAR(50)  NOT NULL COMMENT 'Writer',
  PRIMARY KEY (ID)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = UTF8;
